---
- hosts: lost
  become: yes
  remote_user: user

  tasks:

 - name: Set authorized key took from file
   autohrized_key:
     user: charlie
     state: present
     key: "{{ lookup('file', '/home/charlie/.ssh/id_rsa.pub') }}"

