---
- hosts: databases
  become: yes

  tasks:

  - name: install apache
    yum:
      name: httpd
      state: latest

  - name: create file if doesnt exist
    file:
      state: touch
      path: /var/www/html/index.html

  - name: If line not there then add it.
    lineinfile:
      state: present
      dest: /var/www/html/index.html
      line: Hostname={{ ansible_hostname }}
  
  - name: restart apache
    service:
      name: httpd
      state: reloaded
      enabled: yes
