---
- hosts: all
  become: yes

  tasks:

    - name: install system updates for centos systems
      yum: 
        name: '*' 
        state: latest
        when: ansible_distribution == "CentOS"

    - name: install system updates for ubuntu systems
      apt: 
        name: '*' 
        state: latest
        when: ansible_distribution == "Ubuntu"
