---
- hosts: lost
  become: yes
  gather_facts: no
  remote_user: user 

  tasks:

  - name: install ssh key
    authorized_key: user=ansible
                    key="{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}" state=present
